"""Add oepn_time and close_time columns to cafes table

Revision ID: 055ed8bca2c1
Revises: 9f82754964fe
Create Date: 2026-04-16 13:06:14.895296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055ed8bca2c1'
down_revision = '9f82754964fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('open_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('close_time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafes', schema=None) as batch_op:
        batch_op.drop_column('close_time')
        batch_op.drop_column('open_time')

    # ### end Alembic commands ###
