"""Add is_featured column to Cafe table

Revision ID: 22bd7f792bd9
Revises: b416393233fd
Create Date: 2026-03-17 18:26:06.952481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22bd7f792bd9'
down_revision = 'b416393233fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafes', schema=None) as batch_op:
        batch_op.drop_column('is_featured')

    # ### end Alembic commands ###
