"""add deleted_at column to Cafe model

Revision ID: 9f82754964fe
Revises: ab8d380153ef
Create Date: 2026-03-29 21:25:47.778326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f82754964fe'
down_revision = 'ab8d380153ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafes', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
