"""Add rating association table and constraints

Revision ID: b416393233fd
Revises: 5b80b0c47170
Create Date: 2026-03-13 11:05:17.251779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b416393233fd'
down_revision = '5b80b0c47170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('map_url', sa.String(length=500), nullable=False),
    sa.Column('img_url', sa.String(length=500), nullable=False),
    sa.Column('location', sa.String(length=250), nullable=False),
    sa.Column('seats', sa.String(length=250), nullable=False),
    sa.Column('has_toilet', sa.Boolean(), nullable=False),
    sa.Column('has_wifi', sa.Boolean(), nullable=False),
    sa.Column('has_sockets', sa.Boolean(), nullable=False),
    sa.Column('can_take_calls', sa.Boolean(), nullable=False),
    sa.Column('coffee_price', sa.String(length=250), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_submitted', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cafe')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    op.create_table('cafe',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), nullable=False),
    sa.Column('map_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('img_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('location', sa.VARCHAR(length=250), nullable=False),
    sa.Column('seats', sa.VARCHAR(length=250), nullable=False),
    sa.Column('has_toilet', sa.BOOLEAN(), nullable=False),
    sa.Column('has_wifi', sa.BOOLEAN(), nullable=False),
    sa.Column('has_sockets', sa.BOOLEAN(), nullable=False),
    sa.Column('can_take_calls', sa.BOOLEAN(), nullable=False),
    sa.Column('coffee_price', sa.VARCHAR(length=250), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('ratings')
    op.drop_table('cafes')
    # ### end Alembic commands ###
